### ISSUE TITLE
Icon License

### ISSUE THREAD

**Issue by elbotho** [CIAT-DAPA/cwr_interdependence#16]
Hello!
I love the project and love that it is freely licensed. Thank you very much.
Just to be sure: Are the icons in the repository also licensed under CC-BY? 
Should I credit the same source or did somebody else create them?

Thank you,
Botho

**Comment by ColinKhoury** [comment]
Hi thanks very much! All the data and results are cc-by, but we actually had to buy some of the icons in order to get everything we needed for that map. So unfortunately those icons are not cc-by. Attached is a list of pretty much where we got what we used, in case its helpful. Thanks again. 
[Items_regions_FSProd_for_map_share.xlsx](https://github.com/CIAT-DAPA/cwr_interdependence/files/485956/Items_regions_FSProd_for_map_share.xlsx)

**Comment by elbotho** [comment]
Thank you for the transparency!
There are some people working on freely licensed crop icons. Maybe for your future work they will be far enough :)
https://github.com/openfarmcc/open-crop-icons
https://github.com/serlo-org/open-flat-crop-icons

**Comment by ColinKhoury** [comment]
Sweet! Thank you so much!
Colin

Colin Khoury
