### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by stevensotelo** [CIAT-DAPA/cwr_interdependence#5]
1) Text update (Harold to do in code from gdoc and give code to stevie)
o “explore text” – need to update- done
o West Africa – Cote- done
o Make “hover” bold - done
2) Change “Source” to “Origin” and “Target” to “Consumer” (OR figure out the flecha or other option!
3) Make “Total: xxx” a bit smaller font 
4) Hover box at regions on right gets cutoff? (e.g. C Africa)
5) Cottonseed oil icon seems to be cutoff at left?
6) ***Fix top 5 crops error (Harold working on this)
7) Some regions seem to have weird letters still on the circos (e.g. Temp S America)
8) Consider moving bottom text to an expandable tab or something (called “About the plot”)
9) I think we need to find a way to make more visible in right side data that the values are tonnes, ha, $US million, etc. How to do this?
10) Explore making a map instead of listing of countries

**Comment by ColinKhoury** [comment]
further revisions:
11. change "Consumer" to "Producer" (Only for Production page- is this possible? we want to keep "Consumer" on Diets page)
12. Please bold the name of origin and producer regions at right area that appears
13. Total value- I like what you did with putting at bottom, but think its confusing, because Total NOT = to sum of top 5 crops, so people might be confused. I would keep the total above the crops. Is there maybe a way to put "Top 5 crops" or something above the crops?

**Comment by stevensotelo** [comment]
@ColinKhoury 

2) Fixed
3) FIxed
4) In some cases, when the message is near of the border, the circos cut the image because it is outside the boundary. 
5) Fixed
7) We need to do smaller the text for this case
8) Fixed
9) Fixed
10) Created a new issue for this improve

**Comment by ColinKhoury** [comment]
looks great!
14. change "Top 5 crops" to "Top crops"
15. Change "Consumer" to "Producer" (only on Production page; diets page should stay as "Consumer"). Is this possible? (this ==issue 11)

**Comment by stevensotelo** [comment]
@ColinKhoury 

14) Fixed
15) Fixed

**Comment by ColinKhoury** [comment]
Excellent
